import AppLayout from "@/components/AppLayout";
import GeneratorOutput from "@/components/GeneratorOutput";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { ClipboardList, Download, Loader2, Sparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const NICHES = ["Dental Office", "Real Estate Agent", "Plumber", "HVAC Company", "Med Spa", "Law Firm", "Auto Repair Shop", "Gym / Fitness Studio"];

function markdownToHtml(md: string): string {
  return md
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/^\| (.+) \|$/gm, (_, row) => `<tr>${row.split(" | ").map((c: string) => `<td>${c}</td>`).join("")}</tr>`)
    .replace(/^- \[x\] (.+)$/gm, "<li class='done'>✅ $1</li>")
    .replace(/^- \[ \] (.+)$/gm, "<li class='todo'>☐ $1</li>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/((<li[^>]*>.*<\/li>\n?)+)/g, "<ul>$1</ul>");
}

function exportChecklistPdf(content: string, businessName: string, niche: string) {
  const html = markdownToHtml(content);
  const printWindow = window.open("", "_blank");
  if (!printWindow) { toast.error("Pop-up blocked. Please allow pop-ups for this site."); return; }
  printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Client Onboarding — ${businessName}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@600;700&family=Plus+Jakarta+Sans:wght@400;500;600&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Plus Jakarta Sans', sans-serif; color: #1c1a17; background: #fff; padding: 48px; max-width: 800px; margin: 0 auto; font-size: 13px; line-height: 1.7; }
    .header { border-bottom: 2px solid #b8763f; padding-bottom: 20px; margin-bottom: 32px; }
    .header h1 { font-family: 'Outfit', sans-serif; font-size: 22px; font-weight: 700; }
    .badge { display: inline-block; background: #f6e8da; color: #7a4a1f; padding: 2px 10px; border-radius: 999px; font-size: 11px; font-weight: 600; margin-top: 8px; }
    h2 { font-family: 'Outfit', sans-serif; font-size: 15px; font-weight: 700; margin-top: 28px; margin-bottom: 10px; padding-bottom: 6px; border-bottom: 1px solid #e8e4de; }
    h3 { font-size: 13px; font-weight: 600; margin-top: 16px; margin-bottom: 6px; }
    ul { padding-left: 0; list-style: none; margin-bottom: 10px; }
    li { padding: 5px 0; border-bottom: 1px solid #f3f1ed; font-size: 12px; }
    li.done { color: #6b6862; }
    strong { font-weight: 600; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 12px; }
    td, th { border: 1px solid #e8e4de; padding: 6px 10px; text-align: left; }
    th { background: #f9f7f4; font-weight: 600; }
    .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e8e4de; font-size: 11px; color: #9c9890; text-align: center; }
    @media print { body { padding: 24px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>Client Onboarding Checklist</h1>
    <p>Client: <strong>${businessName}</strong></p>
    <span class="badge">${niche}</span>
    <p style="margin-top:8px;font-size:11px;color:#9c9890">Generated ${new Date().toLocaleDateString()} · Automation Hub</p>
  </div>
  <div>${html}</div>
  <div class="footer">Generated by Automation Hub · Chatbot Agency Toolkit</div>
  <script>window.onload = () => { window.print(); }</script>
</body>
</html>`);
  printWindow.document.close();
}

export default function Onboarding() {
  const [form, setForm] = useState({ businessName: "", niche: "" });
  const [output, setOutput] = useState<string | null>(null);

  const mutation = trpc.generate.onboardingChecklist.useMutation({
    onSuccess: (data) => { setOutput(data.content); toast.success("Onboarding checklist generated!"); },
    onError: (err) => toast.error(err.message || "Generation failed."),
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.businessName || !form.niche) { toast.error("Please fill in all fields."); return; }
    mutation.mutate(form);
  };

  return (
    <AppLayout>
      <div className="p-6 lg:p-10 max-w-3xl mx-auto">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-9 h-9 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center">
            <ClipboardList className="w-5 h-5 text-primary" />
          </div>
          <div>
            <h1 className="font-display text-xl font-semibold tracking-tight text-foreground">Client Onboarding Checklist</h1>
            <p className="text-xs text-muted-foreground">Generate a step-by-step onboarding document for a new chatbot client.</p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="rounded-2xl border border-border bg-card p-6 space-y-5 mb-6">
          <div className="space-y-1.5">
            <Label htmlFor="businessName" className="text-sm font-medium text-foreground">Client Business Name</Label>
            <Input id="businessName" placeholder="e.g. Bright Smile Dental" value={form.businessName}
              onChange={e => setForm(f => ({ ...f, businessName: e.target.value }))} />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="niche" className="text-sm font-medium text-foreground">Business Niche</Label>
            <Input id="niche" placeholder="e.g. Dental Office" value={form.niche}
              onChange={e => setForm(f => ({ ...f, niche: e.target.value }))} />
            <div className="flex flex-wrap gap-1.5 pt-1">
              {NICHES.map(n => (
                <button key={n} type="button" onClick={() => setForm(f => ({ ...f, niche: n }))}
                  className={`px-2.5 py-1 rounded-full text-xs border transition-colors ${
                    form.niche === n
                      ? "bg-primary/15 border-primary/40 text-primary"
                      : "border-border text-muted-foreground hover:border-primary/30 hover:text-foreground"
                  }`}>
                  {n}
                </button>
              ))}
            </div>
          </div>
          <Button type="submit" disabled={mutation.isPending} className="w-full gap-2">
            {mutation.isPending ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating...</> : <><Sparkles className="w-4 h-4" /> Generate Onboarding Checklist</>}
          </Button>
        </form>

        {mutation.isPending && (
          <div className="rounded-2xl border border-border bg-card p-8 flex flex-col items-center gap-3 text-center">
            <Loader2 className="w-6 h-6 text-primary animate-spin" />
            <p className="text-sm text-muted-foreground">AI is building your onboarding checklist...</p>
            <p className="text-xs text-muted-foreground">This may take 10–15 seconds.</p>
          </div>
        )}

        {!mutation.isPending && !output && (
          <div className="rounded-2xl border border-dashed border-border p-10 text-center">
            <ClipboardList className="w-6 h-6 text-muted-foreground/50 mx-auto mb-3" />
            <p className="text-sm text-foreground font-medium mb-1">No checklist yet</p>
            <p className="text-xs text-muted-foreground max-w-xs mx-auto">
              Enter a client name and niche above to generate a phased onboarding checklist.
            </p>
          </div>
        )}

        {output && !mutation.isPending && (
          <div className="space-y-3">
            <div className="flex justify-end">
              <Button variant="outline" size="sm"
                onClick={() => exportChecklistPdf(output, form.businessName, form.niche)}
                className="gap-2 text-xs">
                <Download className="w-3.5 h-3.5" /> Export as PDF
              </Button>
            </div>
            <GeneratorOutput content={output} label="Client Onboarding Checklist" />
          </div>
        )}
      </div>
    </AppLayout>
  );
}
